services:
  redis:
    image: redis:7
    container_name: redis-middleware-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --requirepass @redis_password@
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "-a","@redis_password@","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  redis_data: